spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  session:
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true